//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xFunc.Maths.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("xFunc.Maths.Resources.Resource", typeof(Resource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The expression &apos;{1}&apos; was assigned to the function &apos;{0}&apos;. ähnelt.
        /// </summary>
        internal static string AssignFunction {
            get {
                return ResourceManager.GetString("AssignFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The value &apos;{1}&apos; was assigned to the variable &apos;{0}&apos;. ähnelt.
        /// </summary>
        internal static string AssignVariable {
            get {
                return ResourceManager.GetString("AssignVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You can&apos;t change constants. ähnelt.
        /// </summary>
        internal static string ConstError {
            get {
                return ResourceManager.GetString("ConstError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The parameter #{2} has wrong type (Expected: {0}; Actual: {1}). ähnelt.
        /// </summary>
        internal static string DifferentParameterTypeMismatchExceptionError {
            get {
                return ResourceManager.GetString("DifferentParameterTypeMismatchExceptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An error occurred while parsing the tree. ähnelt.
        /// </summary>
        internal static string ErrorWhileParsingTree {
            get {
                return ResourceManager.GetString("ErrorWhileParsingTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The string &apos;{0}&apos; has an invalid format. ähnelt.
        /// </summary>
        internal static string FormatException {
            get {
                return ResourceManager.GetString("FormatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The &apos;{0}&apos; function not found. ähnelt.
        /// </summary>
        internal static string FunctionNotFoundExceptionError {
            get {
                return ResourceManager.GetString("FunctionNotFoundExceptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The expression is invalid. ähnelt.
        /// </summary>
        internal static string InvalidExpression {
            get {
                return ResourceManager.GetString("InvalidExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The function has an invalid number of variables. ähnelt.
        /// </summary>
        internal static string InvalidNumberOfVariables {
            get {
                return ResourceManager.GetString("InvalidNumberOfVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The left parameter has wrong type (Expected: {0}; Actual: {1}). ähnelt.
        /// </summary>
        internal static string LeftParameterTypeMismatchExceptionError {
            get {
                return ResourceManager.GetString("LeftParameterTypeMismatchExceptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The number of parameters is less than expected. ähnelt.
        /// </summary>
        internal static string LessParams {
            get {
                return ResourceManager.GetString("LessParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The size of matrices is invalid. ähnelt.
        /// </summary>
        internal static string MatrixArgException {
            get {
                return ResourceManager.GetString("MatrixArgException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The number of parameters is more than expected. ähnelt.
        /// </summary>
        internal static string MoreParams {
            get {
                return ResourceManager.GetString("MoreParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Brackets are not balanced. ähnelt.
        /// </summary>
        internal static string NotBalanced {
            get {
                return ResourceManager.GetString("NotBalanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not enough parameters. ähnelt.
        /// </summary>
        internal static string NotEnoughParams {
            get {
                return ResourceManager.GetString("NotEnoughParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The function is not specified. ähnelt.
        /// </summary>
        internal static string NotSpecifiedFunction {
            get {
                return ResourceManager.GetString("NotSpecifiedFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The symbol &apos;{0}&apos; is not supported. ähnelt.
        /// </summary>
        internal static string NotSupportedSymbol {
            get {
                return ResourceManager.GetString("NotSupportedSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Parameter type mismatch (Expected: {0}; Actual: {1}). ähnelt.
        /// </summary>
        internal static string ParameterTypeMismatchExceptionError {
            get {
                return ResourceManager.GetString("ParameterTypeMismatchExceptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You cannot change value of &quot;{0}&quot;. ähnelt.
        /// </summary>
        internal static string ReadOnlyError {
            get {
                return ResourceManager.GetString("ReadOnlyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The right parameter has wrong type (Expected: {0}; Actual: {1}). ähnelt.
        /// </summary>
        internal static string RightParameterTypeMismatchExceptionError {
            get {
                return ResourceManager.GetString("RightParameterTypeMismatchExceptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The sequence cannot contain null values. ähnelt.
        /// </summary>
        internal static string SequenceNullValuesError {
            get {
                return ResourceManager.GetString("SequenceNullValuesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The &apos;{0}&apos; function is removed. ähnelt.
        /// </summary>
        internal static string UndefineFunction {
            get {
                return ResourceManager.GetString("UndefineFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The &apos;{0}&apos; variable is removed. ähnelt.
        /// </summary>
        internal static string UndefineVariable {
            get {
                return ResourceManager.GetString("UndefineVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unexpected error. ähnelt.
        /// </summary>
        internal static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The &apos;{0}&apos; variable not found. ähnelt.
        /// </summary>
        internal static string VariableNotFoundExceptionError {
            get {
                return ResourceManager.GetString("VariableNotFoundExceptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The size of vector should equal to 3. ähnelt.
        /// </summary>
        internal static string VectorCrossException {
            get {
                return ResourceManager.GetString("VectorCrossException", resourceCulture);
            }
        }
    }
}
